// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCZ2mdKRer25muu99g89pB7PKRiEcoNm8k",
   appId: "1:55425028463:web:1fd4a1d8e202d0888ed89a",
   messagingSenderId: "55425028463",
   projectId: "goerlocaldelivery",
    authDomain: "goerlocaldelivery.firebaseapp.com",
     storageBucket: "goerlocaldelivery.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCZ2mdKRer25muu99g89pB7PKRiEcoNm8k",
   appId: "1:55425028463:web:1fd4a1d8e202d0888ed89a",
   messagingSenderId: "55425028463",
   projectId: "goerlocaldelivery",
     storageBucket: "goerlocaldelivery.firebasestorage.app",
  ); 
  
  
//   const firebaseConfig = {
//   apiKey: "AIzaSyCQGCuQHoeNwjGOpysmgyn4990TdLx5mpg",
//   authDomain: "ecappzeto.firebaseapp.com",
//   databaseURL: "https://ecappzeto-default-rtdb.firebaseio.com",
//   projectId: "ecappzeto",
//   storageBucket: "ecappzeto.firebasestorage.app",
//   messagingSenderId: "942766071918",
//   appId: "1:942766071918:web:af12f20132a9ae2538067f",
//   measurementId: "G-KBQ5F0WWCM"
// };

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.firebasestorage.app',
    iosBundleId: 'your-ios-bundle-id',
    iosClientId: 'your-ios-client-id',
  );

}